apiVersion: v1
kind: Pod
metadata:
  name: gcp-secrets-example
  namespace: default
  labels:
    app: secrets-example
spec:
  serviceAccountName: oke-sa
  containers:
  - name: secrets-app
    image: google/cloud-sdk:slim
    command:
    - /bin/bash
    - -c
    - |
      #!/bin/bash
      set -e
      
      echo "Starting GCP Secret Manager example..."
      
      # Wait for token
      sleep 2
      
      # Configure gcloud
      export GOOGLE_APPLICATION_CREDENTIALS=/var/run/secrets/tokens/gcp-ksa
      export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/var/run/secrets/tokens/gcp-ksa
      
      echo "Authenticating with GCP..."
      gcloud auth list
      
      # Get project ID from environment or metadata
      PROJECT_ID="${GCP_PROJECT_ID}"
      
      if [ -z "$PROJECT_ID" ]; then
        echo "ERROR: GCP_PROJECT_ID not set"
        exit 1
      fi
      
      echo "Project ID: ${PROJECT_ID}"
      
      # Example: Access a secret (requires secretmanager.secretAccessor role)
      SECRET_NAME="my-secret"
      
      echo "Accessing secret: ${SECRET_NAME}..."
      gcloud secrets versions access latest \
        --secret="${SECRET_NAME}" \
        --project="${PROJECT_ID}" || echo "Secret not found or permission denied"
      
      # Example: List secrets (requires secretmanager.viewer role)
      echo "Listing secrets..."
      gcloud secrets list --project="${PROJECT_ID}" || echo "Cannot list secrets or permission denied"
      
      echo "Example completed. Sleeping..."
      sleep infinity
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/run/secrets/tokens/gcp-ksa
    - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
      value: /var/run/secrets/tokens/gcp-ksa
    - name: GCP_PROJECT_ID
      value: ""  # Set your GCP project ID here before deploying
    volumeMounts:
    - name: gcp-token
      mountPath: /var/run/secrets/tokens
      readOnly: true
  volumes:
  - name: gcp-token
    projected:
      sources:
      - serviceAccountToken:
          path: gcp-ksa
          expirationSeconds: 3600
          audience: sts.googleapis.com
