apiVersion: v1
kind: Pod
metadata:
  name: gcs-storage-example
  namespace: default
  labels:
    app: gcs-example
spec:
  serviceAccountName: oke-sa
  containers:
  - name: gcs-app
    image: google/cloud-sdk:slim
    command:
    - /bin/bash
    - -c
    - |
      #!/bin/bash
      set -e
      
      echo "Starting GCS storage example..."
      
      # Wait a moment for token to be available
      sleep 2
      
      # Configure gcloud
      export GOOGLE_APPLICATION_CREDENTIALS=/var/run/secrets/tokens/gcp-ksa
      export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/var/run/secrets/tokens/gcp-ksa
      
      echo "Authenticating with GCP..."
      gcloud auth list
      
      echo "Listing GCS buckets..."
      gcloud storage ls || echo "No buckets accessible or permission denied"
      
      # Example: Create a test file and upload
      echo "Creating test file..."
      echo "Hello from OKE pod at $(date)" > /tmp/test.txt
      
      # Upload to GCS (requires storage.objectCreator role)
      # Uncomment if you have write permissions
      # BUCKET_NAME="your-bucket-name"
      # echo "Uploading to gs://${BUCKET_NAME}/test.txt..."
      # gcloud storage cp /tmp/test.txt gs://${BUCKET_NAME}/test.txt
      
      # Keep container running
      echo "Example completed. Sleeping..."
      sleep infinity
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/run/secrets/tokens/gcp-ksa
    - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
      value: /var/run/secrets/tokens/gcp-ksa
    volumeMounts:
    - name: gcp-token
      mountPath: /var/run/secrets/tokens
      readOnly: true
  volumes:
  - name: gcp-token
    projected:
      sources:
      - serviceAccountToken:
          path: gcp-ksa
          expirationSeconds: 3600
          audience: sts.googleapis.com
